### ISSUE TITLE
npm install - npm ERR! premature close

### ISSUE THREAD

**Issue by piotr-gomola** [stisla/stisla#141]
Hi,
I can't install dependencies:
```
$ npm install
npm WARN deprecated nicescroll@3.7.4: Please use official npm package at https://www.npmjs.com/package/jquery.nicescroll
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm ERR! premature close

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/piotrek/.npm/_logs/2020-01-07T18_10_35_722Z-debug.log
```

```
$ cat /home/piotrek/.npm/_logs/2020-01-07T18_10_35_722Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/home/piotrek/.nvm/versions/node/v10.17.0/bin/node',
1 verbose cli   '/home/piotrek/.nvm/versions/node/v10.17.0/bin/npm',
1 verbose cli   'install' ]
2 info using npm@6.11.3
3 info using node@v10.17.0
4 verbose npm-session d936ffcdb7712b0f
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall stisla-dev@1.0.0
7 info lifecycle stisla-dev@1.0.0~preinstall: stisla-dev@1.0.0
8 silly install loadCurrentTree
9 silly install readLocalPackageData
10 timing stage:loadCurrentTree Completed in 26ms
11 silly install loadIdealTree
...
2320 silly fetchPackageMetaData error for jquery-pwstrength@git+https://github.com/matoilic/jquery.pwstrength.git premature close
2321 silly fetchPackageMetaData error for jquery_upload_preview@git+https://github.com/opoloo/jquery_upload_preview.git premature close
2322 info lifecycle jqvmap@1.5.1~prepack: jqvmap@1.5.1
2323 info lifecycle jqvmap@1.5.1~postpack: jqvmap@1.5.1
2324 silly pacote git manifest for jqvmap@git+https://github.com/10bestdesign/jqvmap.git fetched in 25304ms
2325 silly resolveWithNewModule jqvmap@1.5.1 checking installable status
2326 timing stage:rollbackFailedOptional Completed in 0ms
2327 timing stage:runTopLevelLifecycles Completed in 38424ms
2328 silly saveTree stisla-dev@1.0.0
2328 silly saveTree ├── @fortawesome/fontawesome-free@5.12.0
2328 silly saveTree ├─┬ bootstrap-colorpicker@3.2.0
2328 silly saveTree │ ├── bootstrap@4.4.1
2328 silly saveTree │ ├── jquery@3.4.1
2328 silly saveTree │ └── popper.js@1.16.0
2328 silly saveTree ├─┬ bootstrap-daterangepicker@3.0.5
2328 silly saveTree │ └── moment@2.24.0
2328 silly saveTree ├── bootstrap-social@5.1.1
2328 silly saveTree ├── bootstrap-tagsinput@0.7.1
2328 silly saveTree ├── bootstrap-timepicker@0.5.2
2328 silly saveTree ├── bootstrap@4.4.1
2328 silly saveTree ├── chart.js@2.9.3
2328 silly saveTree ├── chocolat@0.4.21
2328 silly saveTree ├── cleave.js@1.5.3
2328 silly saveTree ├── codemirror@5.50.2
2328 silly saveTree ├── datatables.net-responsive-bs4@2.2.3
2328 silly saveTree ├── datatables.net-select-bs4@1.3.1
2328 silly saveTree ├── datatables@1.10.18
2328 silly saveTree ├── dropzone@5.5.1
2328 silly saveTree ├── flag-icon-css@3.4.5
2328 silly saveTree ├── fullcalendar@3.10.1
2328 silly saveTree ├── gmaps@0.4.24
2328 silly saveTree ├── ionicons201@1.0.0
2328 silly saveTree ├── izitoast@1.4.0
2328 silly saveTree ├── jquery-sparkline@2.4.0
2328 silly saveTree ├── jquery-ui-dist@1.12.1
2328 silly saveTree ├── jquery.nicescroll@3.7.6
2328 silly saveTree ├── jquery@3.4.1
2328 silly saveTree ├── jqvmap@1.5.1
2328 silly saveTree ├── moment@2.24.0
2328 silly saveTree ├── nicescroll@3.7.4
2328 silly saveTree ├── owl.carousel@2.3.4
2328 silly saveTree ├── perfect-scrollbar@1.4.0
2328 silly saveTree ├── popper.js@1.16.0
2328 silly saveTree ├── prismjs@1.18.0
2328 silly saveTree ├── select2@4.0.12
2328 silly saveTree ├── selectric@1.13.0
2328 silly saveTree ├── simpleweather@3.1.0
2328 silly saveTree ├── sticky-kit@1.1.3
2328 silly saveTree ├── summernote@0.8.15
2328 silly saveTree ├── sweetalert@2.1.2
2328 silly saveTree ├── tooltip.js@1.3.3
2328 silly saveTree └── weathericons@2.1.0
2329 verbose stack Error: premature close
2329 verbose stack     at PassThrough.onclose (/home/piotrek/.nvm/versions/node/v10.17.0/lib/node_modules/npm/node_modules/end-of-stream/index.js:47:67)
2329 verbose stack     at PassThrough.emit (events.js:203:15)
2329 verbose stack     at emitCloseNT (internal/streams/destroy.js:68:8)
2329 verbose stack     at process._tickCallback (internal/process/next_tick.js:63:19)
2330 verbose cwd /mnt/storage/projects/HIDDEN
2331 verbose Linux 4.15.0-74-generic
2332 verbose argv "/home/piotrek/.nvm/versions/node/v10.17.0/bin/node" "/home/piotrek/.nvm/versions/node/v10.17.0/bin/npm" "install"
2333 verbose node v10.17.0
2334 verbose npm  v6.11.3
2335 error premature close
2336 verbose exit [ 1, true 
```

**Comment by piotr-gomola** [comment]
However...

```
$ npm run stisla-start

> stisla-dev@1.0.0 stisla-start /mnt/storage/projects/HIDDEN
> yarn install --production=false

yarn install v1.21.1
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 26.47s.
```

```
$ npm run dist

> stisla-dev@1.0.0 dist /mnt/storage/projects/HIDDEN
> gulp dist

[19:21:30] Using gulpfile /mnt/storage/projects/HIDDEN/gulpfile.js
[19:21:30] Starting 'dist'...
[19:21:30] Starting 'folder'...
[19:21:30] Starting 'compile_scss'...
[19:21:30] Starting 'compile_html'...
[19:21:30] Finished 'folder' after 212 ms
Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
[19:21:32] Finished 'compile_scss' after 1.49 s
[19:21:32] Finished 'compile_html' after 1.93 s
[19:21:32] Finished 'dist' after 1.94 s

```
I am no frontend developer, but shouldn't be there a `dist` dir after "build" operation?

**Comment by nauvalazhar** [comment]
Hi, please use Yarn instead. 

> I am no frontend developer, but shouldn't be there a dist dir after "build" operation?

No, it's not. You need to install the dependencies first, then all sources will be compiled into the dist folder.
