### ISSUE TITLE
Failing to install

### ISSUE THREAD

**Issue by c0fe** [stisla/stisla#150]
**Steps to Reproduce:**

1. Run `git clone https://github.com/stisla/stisla.git stisla`
2. Enter stisla directory
3. Run `npm install`

**Environment:**
_Ubuntu:_ 18.04 (latest updates installed)
_NodeJS:_ 13.10.0
_NPM:_  6.13.7

**Error Log:**

```
3863 silly fetchPackageMetaData error for jquery-pwstrength@git+https://github.com/matoilic/jquery.pwstrength.git premature close
3864 silly fetchPackageMetaData error for jquery_upload_preview@git+https://github.com/opoloo/jquery_upload_preview.git premature close
3865 info lifecycle jqvmap@1.5.1~prepack: jqvmap@1.5.1
3866 info lifecycle jqvmap@1.5.1~postpack: jqvmap@1.5.1
3867 silly pacote git manifest for jqvmap@git+https://github.com/10bestdesign/jqvmap.git fetched in 10637ms
3868 silly resolveWithNewModule jqvmap@1.5.1 checking installable status
3869 timing stage:rollbackFailedOptional Completed in 1ms
3870 timing stage:runTopLevelLifecycles Completed in 64260ms
3871 silly saveTree stisla-dev@1.0.0
3871 silly saveTree ├── @fortawesome/fontawesome-free@5.12.1
3871 silly saveTree ├─┬ bootstrap-colorpicker@3.2.0
3871 silly saveTree │ ├── bootstrap@4.4.1
3871 silly saveTree │ ├── jquery@3.4.1
3871 silly saveTree │ └── popper.js@1.16.1
3871 silly saveTree ├─┬ bootstrap-daterangepicker@3.0.5
3871 silly saveTree │ └── moment@2.24.0
3871 silly saveTree ├── bootstrap-social@5.1.1
3871 silly saveTree ├── bootstrap-tagsinput@0.7.1
3871 silly saveTree ├── bootstrap-timepicker@0.5.2
3871 silly saveTree ├── bootstrap@4.4.1
3871 silly saveTree ├── chart.js@2.9.3
3871 silly saveTree ├── chocolat@0.4.21
3871 silly saveTree ├── cleave.js@1.5.7
3871 silly saveTree ├── codemirror@5.52.0
3871 silly saveTree ├── datatables.net-responsive-bs4@2.2.3
3871 silly saveTree ├── datatables.net-select-bs4@1.3.1
3871 silly saveTree ├── datatables@1.10.18
3871 silly saveTree ├── dropzone@5.7.0
3871 silly saveTree ├── flag-icon-css@3.4.6
3871 silly saveTree ├── fullcalendar@3.10.1
3871 silly saveTree ├── gmaps@0.4.25
3871 silly saveTree ├── ionicons201@1.0.0
3871 silly saveTree ├── izitoast@1.4.0
3871 silly saveTree ├── jquery-sparkline@2.4.0
3871 silly saveTree ├── jquery-sparkline@2.4.0
3871 silly saveTree ├── jquery-ui-dist@1.12.1
3871 silly saveTree ├── jquery.nicescroll@3.7.6
3871 silly saveTree ├── jquery@3.4.1
3871 silly saveTree ├── jqvmap@1.5.1
3871 silly saveTree ├── moment@2.24.0
3871 silly saveTree ├── nicescroll@3.7.4
3871 silly saveTree ├── owl.carousel@2.3.4
3871 silly saveTree ├── perfect-scrollbar@1.5.0
3871 silly saveTree ├── popper.js@1.16.1
3871 silly saveTree ├── prismjs@1.19.0
3871 silly saveTree ├── select2@4.0.13
3871 silly saveTree ├── selectric@1.13.0
3871 silly saveTree ├── simpleweather@3.1.0
3871 silly saveTree ├── sticky-kit@1.1.3
3871 silly saveTree ├── summernote@0.8.16
3871 silly saveTree ├── sweetalert@2.1.2
3871 silly saveTree ├── tooltip.js@1.3.3
3871 silly saveTree └── weathericons@2.1.0
3872 verbose stack Error: premature close
3872 verbose stack     at PassThrough.onclose (/usr/lib/node_modules/npm/node_modules/end-of-stream/index.js:47:67)
3872 verbose stack     at PassThrough.emit (events.js:333:22)
3872 verbose stack     at emitCloseNT (internal/streams/destroy.js:80:8)
3872 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:83:21)
3873 verbose cwd /var/www/admin2
3874 verbose Linux 4.15.0-88-generic
3875 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
3876 verbose node v13.10.0
3877 verbose npm  v6.13.7
3878 error premature close
3879 verbose exit [ 1, true 
```]

**Comment by nauvalazhar** [comment]
Hi thank you for reporting this issue. Please use Yarn instead.

**Comment by c0fe** [comment]
@nauvalazhar you should update your documentation to remove npm references if it isn't being supported by this project.
