### ISSUE TITLE
Penemuan bug ketika install pertama kali

### ISSUE THREAD

**Issue by alan96320** [stisla/stisla#208]
menurut dokumentasi yang tertera.
1. clone atau download file stisla
2. lalu masuk ke dalam folder stisla
3. lalu jika dikomputer kita beum memiliki npm dan yarn, maka harus di install terlebih dahulu npm dan yarn.
4. lalu jika sudah maka jalankan yarn.
5. done.

lalu saya mencoba step by step langkah di atas, pada saat yang melakukan langka nomor 4, terdapat errror
![image](https://user-images.githubusercontent.com/22470002/128627946-c3aa1deb-7b06-4243-9dbd-cc025b23499d.png)
dan setelah saya telusuri ternyata kesalahannya ada pada file yarn.lock
jadi saran saya lebih baik di ignore saja pada git untuk file yarn.lock supaya tidak terjadi kesalahan lagi pada yang lain.

dan saya mau moncoba ikut berkontibusi dalam pengembangan. ijin ya mas.

**Comment by oimtrust** [comment]
Thank you kak @alan96320

**Comment by alan96320** [comment]
oh iya saya ada, minta pull request, saya menambahkan thema dan schema. bisa minta di tinjau mas.

**Comment by oimtrust** [comment]
Btw solusinya supaya lancar install `yarn` gimana ya kak @alan96320 ? Ini aku coba ternyata masih error

**Comment by alan96320** [comment]
> Btw solusinya supaya lancar install `yarn` gimana ya kak @alan96320 ? Ini aku coba ternyata masih error

setelah download atau clone, hapua yarn.lock nya baru instal yarn nya.

dan kalau masih error, sertakan ss errornya

**Comment by oimtrust** [comment]
Masih error:
```
/Users/oimtrust/.node-gyp/16.2.0/include/node/v8-internal.h:452:38: error: no template named 'remove_cv_t' in namespace 'std'; did you mean 'remove_cv'?
            !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
                                ~~~~~^~~~~~~~~~~
                                     remove_cv
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/type_traits:776:50: note: 'remove_cv' declared here
template <class _Tp> struct _LIBCPP_TEMPLATE_VIS remove_cv
                                                 ^
1 error generated.
make: *** [Release/obj.target/binding/src/binding.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/oimtrust/Sites/stisla/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (node:events:365:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Darwin 20.5.0
gyp ERR! command "/usr/local/Cellar/node/16.2.0/bin/node" "/Users/oimtrust/Sites/stisla/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/oimtrust/Sites/stisla/node_modules/node-sass
gyp ERR! node -v v16.2.0
gyp ERR! node-gyp -v v3.8.0
```

**Comment by alan96320** [comment]
> Masih error:
> 
> ```
> /Users/oimtrust/.node-gyp/16.2.0/include/node/v8-internal.h:452:38: error: no template named 'remove_cv_t' in namespace 'std'; did you mean 'remove_cv'?
>             !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
>                                 ~~~~~^~~~~~~~~~~
>                                      remove_cv
> /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/type_traits:776:50: note: 'remove_cv' declared here
> template <class _Tp> struct _LIBCPP_TEMPLATE_VIS remove_cv
>                                                  ^
> 1 error generated.
> make: *** [Release/obj.target/binding/src/binding.o] Error 1
> gyp ERR! build error
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/Users/oimtrust/Sites/stisla/node_modules/node-gyp/lib/build.js:262:23)
> gyp ERR! stack     at ChildProcess.emit (node:events:365:28)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
> gyp ERR! System Darwin 20.5.0
> gyp ERR! command "/usr/local/Cellar/node/16.2.0/bin/node" "/Users/oimtrust/Sites/stisla/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
> gyp ERR! cwd /Users/oimtrust/Sites/stisla/node_modules/node-sass
> gyp ERR! node -v v16.2.0
> gyp ERR! node-gyp -v v3.8.0
> ```

coba ikuti langkah di video ini mas, seharusnya jika sudah mengikuti ini tida ada error.
https://youtu.be/UvT3ajHo4Uc
