### ISSUE TITLE
Error while running npm install

### ISSUE THREAD

**Issue by keynesfariz** [stisla/stisla#41]
Hi, I'm sorry for reporting this error, I'm new to this gulp thing.

So I ran "npm install" and/or "npm install --save-dev" and I got this error
```
2323 verbose stack Error: premature close
2323 verbose stack     at PassThrough.onclose (C:\Program Files\nodejs\node_modules\npm\node_modules\end-of-stream\index.js:47:67)
2323 verbose stack     at PassThrough.emit (events.js:194:15)
2323 verbose stack     at emitCloseNT (internal/streams/destroy.js:59:8)
2323 verbose stack     at process._tickCallback (internal/process/next_tick.js:63:19)
2324 verbose cwd D:\Projects\stisla
2325 verbose Windows_NT 10.0.17763
2326 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
2327 verbose node v10.15.3
2328 verbose npm  v6.4.1
2329 error premature close
2330 verbose exit [ 1, true ]
```
I am using Node.js v10.15.3, npm v.6.4.1. Thank you for any help

**Comment by nauvalazhar** [comment]
Hi, please use Yarn instead. 
```
yarn stisla-start # install all dependencies
yarn dev # to start developing
```

**Comment by keynesfariz** [comment]
> Hi, please use Yarn instead.
> 
> ```
> yarn stisla-start # install all dependencies
> yarn dev # to start developing
> ```

Thank you so much!! I thought yarn was only working linux or something

**Comment by ranzeplay** [comment]
Hope can fix npm install failure
